library(tidyverse)
library(googlesheets4)

# helper functions -----
create_yaml <- function(title, authors, categories){
  yaml_break <-"---"
  tit <- paste("title:", shQuote(title))
  dat <- paste("date:", Sys.Date())
  authors <- stringr::str_c(shQuote(authors), collapse=" , ")
  authors <- paste0("[", authors,"]")
  aut <- paste("authors:", authors)
  lay <- "layout: post"
  # categories come shQuoted properly from parse_tags()
  categories <- paste0("[", categories,"]")
  catt <- paste("categories:", categories)
  # tags are the same as categories for now...
  tagg <- paste("tags:", categories)

  # make the yaml
  output <- paste(yaml_break,
                  tit,
                  dat,
                  aut,
                  lay,
                  catt,
                  tagg,
                  yaml_break, sep = "\n")
  return(output)

}

create_body <- function(title, image, description, authors, website, video, post_author){
  title <- clean_post_title(title)
  #print titles
  #print(title)
  # make folder on posts if it doesn't exist
  root = "content/en/post"
  if(title %in% list.files(root) == FALSE){
    # make dir
    dir.create(file.path(root, title))
  }
  # download image and return the new path
  image <- get_image(image_link = image, path = file.path(root, title))
  # add the "![]()"
  # if the name is called "featured" we don't need to link to it in the post
  #image <- paste0("![](", image, ")")

  # bind things into "description"
  if (is.na(video)){
    description <- paste(description,
                         "## Project Author(s)",
                         authors,
                         "## Project Links",
                         website,
                         "***",
                         "This post was automatically generated by",
                         post_author,
                         sep="\n")
  } else {

    # short cut is {{< youtube w7Ft2ymGmfc >}}
    # emb_video <- paste("{{< youtube")

    description <- paste(description,
                         "## Project Author(s)",
                         authors,
                         "## Project Links",
                         website,
                         "## Project Video",
                         video,
                         "***",
                         "This post was automatically generated by",
                         post_author,
                         sep="\n")
  }

  # paste things
  output <- paste(
    # image,
    description,
    '***',
    sep="\n")
  return(output)
  }

get_image <- function(image_link, path){

  # we will default to our logo when things are nasty on the image side
  our_logo <- "https://raw.githubusercontent.com/open-neuroscience/open-neuroscience-website/master/content/en/authors/admin/avatar.png"

  url <- case_when(str_detect(image_link, "png") ~ str_extract(image_link, ".+png"),
                   str_detect(image_link, "jpg") ~ str_extract(image_link, ".+jpg"),
                   str_detect(image_link, "gif") ~ str_extract(image_link, ".+gif"),
                   str_detect(image_link, "svg") ~ str_extract(image_link, ".+svg"),
                   # When it doesn't detect, we will fall back to the logo image
                   TRUE ~ our_logo
                   )

  filename <- case_when(
    str_detect(image_link, "png") ~ file.path(path, "featured.png"),
    str_detect(image_link, "jpg") ~ file.path(path, "featured.jpg"),
    str_detect(image_link, "gif") ~ file.path(path, "featured.gif"),
    str_detect(image_link, "svg") ~ file.path(path, "featured.svg"),
    # we need to fail with featured.png because our logo image is .png
    TRUE ~ file.path(path, "featured.png")
  )

  # check whether there's a problem with the image
  if(url == our_logo){
    write.table(paste("problem with", image_link),
                file = paste0(tools::file_path_sans_ext(filename), ".txt"),
                row.names = FALSE)
  }

  # if this thing is not an URL it will fail
  url <- download.file(url, filename, mode = "wb")

  # check if the image can be loaded
  img <- try(imager::load.image(filename))
  if (class(img) == "try-error" & str_detect(filename, pattern = "svg") == FALSE){
    write.table(paste("problem with", image_link),
                file = paste0(tools::file_path_sans_ext(filename), ".txt"),
                row.names = FALSE)
    # move the logo into featured
    file.copy("content/en/authors/admin/avatar.png",
              filename,
              overwrite = TRUE)

  }
  print(filename)
  return(filename)
}

write_md <- function(filename, content){
  fileConn <- file(filename)
  writeLines(content, fileConn)
  close(fileConn)
}

parse_tags <- function(df){
  df %>%
    select(starts_with("Project categories")) %>%
    group_by(row=row_number()) %>%
    pivot_longer(cols = starts_with("Project")) %>%
    filter(value != "NA") %>%
    summarise(categories = paste(shQuote(value), collapse=",")) %>%
    pull(categories)

}

clean_post_title <- function(dirty_title, with_path = FALSE){
  # make filename
  clean_title = gsub(x =  dirty_title, pattern = " ", replacement = "_")
  # remove all other punctuation things
  clean_title = stringr::str_replace_all(string = clean_title,
                                      pattern="[[:punct:]]",
                                      replacement="_")
  # this process might create multiple underscores
  #remove triple underscore
  clean_title = gsub(x = clean_title , pattern = "_+", replacement = "_")
  if (with_path == TRUE){
    # create file path
    clean_title = file.path("content/en/post", clean_title, "index.md")
  }
  return(clean_title)
}


# this is the ID
ID <- "1qF5P8RKBSiE6qyInIoTBHdq2m9o5ZnvhnGKkmaJ83uI"
gs4_auth("openeuroscience@gmail.com")
target <- read_sheet(ID)
# this comes handy for later,
# so that we don't add a bunch of columns when we write back
original_columns <- names(target)

# parse tags
target$tags <- parse_tags(target)
# do big changes
post_df <- target %>%
  filter(is.na(posted)|posted==FALSE) %>%
  mutate(filename = clean_post_title(`Project Title`, with_path = TRUE)) %>%
  # we could have repeated posts maybe worth to check in the future
  # distinct()
  # we need to apply the functions rowwise
  rowwise() %>%
  mutate(yaml = create_yaml(`Project Title`, "admin", tags),
         body = create_body(
           title = `Project Title`,
           image = `Link to raw image of your project`,
           description = `Description of the project`,
           authors = `Project Author`,
           website = `Link to Project Website or GitHub repository`,
           video = `[OPTIONAL] Link to video for your project`,
         post_author = `Post Author`),
         post = paste(yaml, body, sep ="\n"))

# actually write
lapply(1:nrow(post_df), function(x) write_md(post_df$filename[x], post_df$post[x]))

# change posted to TRUE on google sheets
# I think it is safe to overwrite directly here

target$posted <- clean_post_title(target$`Project Title`, with_path = FALSE) %in%
  list.files("content/en/post/")

# overwrite the original!
write_sheet(target %>% select(original_columns),ss = ID, sheet=1)
