library(tidyverse)
library(googlesheets4)
# helper functions -----
create_yaml <- function(title, authors, categories, project_handle){
  yaml_break <-"---"
  tit <- paste("title:", shQuote(title))
  dat <- paste("date:", Sys.Date())
  authors <- stringr::str_c(shQuote(authors), collapse=" , ")
  authors <- paste0("[", authors,"]")
  aut <- paste("authors:", authors)
  lay <- "layout: post"
  # categories come shQuoted properly from parse_tags()
  categories <- paste0("[", categories,"]")
  catt <- paste("categories:", categories)
  # tags are the same as categories for now...
  tagg <- paste("tags:", categories)
  # links for sharing
  # read from template
  yaml_list <- yaml::read_yaml("links_template.yaml")
  # if no author supplied, use openneurosci
  if (is.na(project_handle)) {
    yaml_list$links[[1]]$url <- glue::glue("{yaml_list$links[[1]]$url}/openneurosci")
  } else {
    # make sure it's just the first thing
    project_split <- stringr::str_split(project_handle, pattern = ",|;") %>% unlist()
    project_split <- project_split[1]
    yaml_list$links[[1]]$url <- glue::glue("{yaml_list$links[[1]]$url}/{project_split}")
  }
  # make it back to \n separated format
  links <-  yaml_list %>% yaml::as.yaml()

  # make the yaml
  output <- paste(yaml_break,
                  tit,
                  dat,
                  aut,
                  lay,
                  catt,
                  tagg,
                  links,
                  yaml_break, sep = "\n")
  return(output)

}

create_body <- function(title, image, description, authors, website, video, post_author){
  title <- clean_post_title(title)
  #print titles
  #print(title)
  # make folder on posts if it doesn't exist
  root = "content/en/post"
  if(title %in% list.files(root) == FALSE){
    # make dir
    dir.create(file.path(root, title))
  }
  # download image and return the new path
  image <- get_image(image_link = image, path = file.path(root, title))
  # add the "![]()"
  # if the name is called "featured" we don't need to link to it in the post
  #image <- paste0("![](", image, ")")

  # bind things into "description"
  if (is.na(video)){
    description <- paste(description,
                         "## Project Author(s)",
                         authors,
                         "## Project Links",
                         website,
                         "***",
                         "This post was automatically generated by",
                         post_author,
                         sep="\n")
  } else {
    # We only do this for youtube videos, which have this format
    # https://www.youtube.com/watch?v=5oWGBUMJON8&feature=emb_title

    # detect desired pattern
    is_youtu <- stringr::str_detect(video, pattern = "youtu")
    if (is_youtu) {
      # extract video
      emb_code <- get_youtube_id(video)
      # short-cut is {{< youtube w7Ft2ymGmfc >}}
      video <- glue::glue('{{<youtube ',  {emb_code},'>}}',
                          # needed so that we don't lose one { at each end
                          .open = "{{{",
                          .close= "}}}")
      # generate shortcut
    } else {
      # do nothing, use video link as is
    }

    description <- paste(description,
                         "## Project Author(s)",
                         authors,
                         "## Project Links",
                         website,
                         "## Project Video",
                         video,
                         "***",
                         "This post was automatically generated by",
                         post_author,
                         sep="\n")
  }

  # paste things
  output <- paste(
    # image,
    description,
    '***',
    sep="\n")
  return(output)
  }

get_image <- function(image_link, path){

  # we will default to our logo when things are nasty on the image side
  our_logo <- "https://raw.githubusercontent.com/open-neuroscience/open-neuroscience-website/master/content/en/authors/admin/avatar.png"

  url <- case_when(str_detect(image_link, "png") ~ str_extract(image_link, ".+png"),
                   str_detect(image_link, "jpg") ~ str_extract(image_link, ".+jpg"),
                   str_detect(image_link, "gif") ~ str_extract(image_link, ".+gif"),
                   str_detect(image_link, "svg") ~ str_extract(image_link, ".+svg"),
                   # When it doesn't detect, we will fall back to the logo image
                   TRUE ~ our_logo
                   )

  filename <- case_when(
    str_detect(image_link, "png") ~ file.path(path, "featured.png"),
    str_detect(image_link, "jpg") ~ file.path(path, "featured.jpg"),
    str_detect(image_link, "gif") ~ file.path(path, "featured.gif"),
    str_detect(image_link, "svg") ~ file.path(path, "featured.svg"),
    # we need to fail with featured.png because our logo image is .png
    TRUE ~ file.path(path, "featured.png")
  )

  # check whether there's a problem with the image
  if(url == our_logo){
    write.table(paste("problem with", image_link),
                file = paste0(tools::file_path_sans_ext(filename), ".txt"),
                row.names = FALSE)
  }

  # if this thing is not an URL it will fail
  url <- download.file(url, filename, mode = "wb")

  # check if the image can be loaded
  img <- try(imager::load.image(filename))
  if (class(img) == "try-error" && str_detect(filename, pattern = "svg") == FALSE){
    write.table(paste("problem with", image_link),
                file = paste0(tools::file_path_sans_ext(filename), ".txt"),
                row.names = FALSE)
    # move the logo into featured
    file.copy("content/en/authors/admin/avatar.png",
              filename,
              overwrite = TRUE)

  }
  print(filename)
  return(filename)
}

write_md <- function(filename, content){
  fileConn <- file(filename)
  writeLines(content, fileConn)
  close(fileConn)
}

parse_tags <- function(df){
  # This function subsets all the project categories from the data frame
  # Then collapses the ones from each post to vectors of the like
  # "a,b,c" instead of c("a", "b", "c")
  # This is needed for pasting directly in create_yaml()
  df %>%
    select(starts_with("Project categories")) %>%
    group_by(row=row_number()) %>%
    pivot_longer(cols = starts_with("Project")) %>%
    filter(value != "NA") %>%
    summarise(categories = paste(shQuote(value), collapse=",")) %>%
    pull(categories)

}

clean_post_title <- function(dirty_title, with_path = FALSE){
  # Post titles have a huge amount of garbage on them
  # That will create troublesome URLs and Folders
  # we can use the with_path boolean to toggle creation of folders
  # in proper destination

  # remove whitespaces
  clean_title = gsub(x =  dirty_title, pattern = " ", replacement = "_")
  # remove all other punctuation
  clean_title = stringr::str_replace_all(string = clean_title,
                                      pattern="[[:punct:]]",
                                      replacement="_")
  # this process might create multiple underscores
  # so remove multiple underscore
  clean_title = gsub(x = clean_title , pattern = "_+", replacement = "_")
  if (with_path == TRUE){
    # create file path
    clean_title = file.path("content/en/post", clean_title, "index.md")
  }
  return(clean_title)
}

get_youtube_id <- function(link) {
  # function extracts id using regex, not panacea, but good enough
  # https://stackoverflow.com/questions/45441896/extract-youtube-video-id-from-url-with-r-stringr-regex
  if (stringr::str_detect(link, '/watch\\?')) {
    rgx = '(?<=\\?v=|&v=)[\\w]+'
  } else {
    rgx = '(?<=/)[\\w]+/?(?:$|\\?)'
  }
  stringr::str_extract(link, rgx)
}


# Script starts here ------------------------------------------------------

# this is the ID
ID <- "1qF5P8RKBSiE6qyInIoTBHdq2m9o5ZnvhnGKkmaJ83uI"
#gs4_auth("openeuroscience@gmail.com")
gs4_deauth()
target <- read_sheet(ID)
# this comes handy for later,
# so that we don't add a bunch of columns when we write back
original_columns <- names(target)

# parse tags
target$tags <- parse_tags(target)
# do big changes
post_df <- target %>%
  filter(is.na(posted)|posted==FALSE) %>%
  mutate(filename = clean_post_title(`Project Title`, with_path = TRUE)) %>%
  # we could have repeated posts maybe worth to check in the future
  # distinct()
  # we need to apply the functions rowwise
  rowwise() %>%
  mutate(yaml = create_yaml(`Project Title`, "admin", tags, `Project Author Twitter handle`),
         body = create_body(
           title = `Project Title`,
           image = `Link to raw image of your project`,
           description = `Description of the project`,
           authors = `Project Author`,
           website = `Link to Project Website or GitHub repository`,
           video = `Link to video for your project`,
         post_author = `Post Author`),
         post = paste(yaml, body, sep ="\n"))

# actually write
lapply(1:nrow(post_df), function(x) write_md(post_df$filename[x], post_df$post[x]))

# change posted to TRUE on google sheets
# I think it is safe to overwrite directly here

target$posted <- clean_post_title(target$`Project Title`, with_path = FALSE) %in%
  list.files("content/en/post/")

# overwrite the original!
write_sheet(target %>% select(original_columns),ss = ID, sheet=1)
